package com.ygy.mapper;

import com.ygy.model.Timeline;
import com.ygy.model.TimelineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimelineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    int countByExample(TimelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    int deleteByExample(TimelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    int insert(Timeline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    int insertSelective(Timeline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    List<Timeline> selectByExample(TimelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    Timeline selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") Timeline record, @Param("example") TimelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    int updateByExample(@Param("record") Timeline record, @Param("example") TimelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    int updateByPrimaryKeySelective(Timeline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    int updateByPrimaryKey(Timeline record);

    /**
     * 刷新动态
     * @return
     */
    List<Timeline> selectByTime();

    /**
     * 查询用户全部动态
     * @param userid
     * @return
     */
    List<Timeline> selectByUserID(long userid);
}