package com.ygy.mapper;

import com.ygy.model.Usertimeline;
import com.ygy.model.UsertimelineExample;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface UsertimelineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertimeline
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    int countByExample(UsertimelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertimeline
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    int deleteByExample(UsertimelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertimeline
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    int insert(Usertimeline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertimeline
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    int insertSelective(Usertimeline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertimeline
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    List<Usertimeline> selectByExample(UsertimelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertimeline
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Usertimeline record, @Param("example") UsertimelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertimeline
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    int updateByExample(@Param("record") Usertimeline record, @Param("example") UsertimelineExample example);

    /**
     * 通过userid查询tid
     *
     * @param userid
     * @return
     */
    List<Long> selectByUid(String userid);
}