eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  redis:
           database: 1
           host: 127.0.0.1
           port: 6379
           password:
           pool:
             max-active: 8
             max-wait: -1
             max-idle: 8
             min-idle: 0
           timeout: 600000
zuul:
  routes:
      api-a:
          path: /api-a/**
          serviceId: service-feign
      api-b:
          path: /api-b/**
          serviceId: service2
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
debug: true

