package com.ygy.model;

import org.springframework.stereotype.Component;
@Component
public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.puserid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    private Long puserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.text
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.thumbsup
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    private Integer thumbsup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.tid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    private Long tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.cid
     *
     * @return the value of comment.cid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.cid
     *
     * @param cid the value for comment.cid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userid
     *
     * @return the value of comment.userid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userid
     *
     * @param userid the value for comment.userid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.puserid
     *
     * @return the value of comment.puserid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public Long getPuserid() {
        return puserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.puserid
     *
     * @param puserid the value for comment.puserid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public void setPuserid(Long puserid) {
        this.puserid = puserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.text
     *
     * @return the value of comment.text
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.text
     *
     * @param text the value for comment.text
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.thumbsup
     *
     * @return the value of comment.thumbsup
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public Integer getThumbsup() {
        return thumbsup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.thumbsup
     *
     * @param thumbsup the value for comment.thumbsup
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public void setThumbsup(Integer thumbsup) {
        this.thumbsup = thumbsup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.tid
     *
     * @return the value of comment.tid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.tid
     *
     * @param tid the value for comment.tid
     *
     * @mbggenerated Sat May 26 17:30:14 CST 2018
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }
}