package com.ygy.model;

import java.util.Date;

public class Timeline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.id
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    private Long id;
    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.userid
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.text
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.file
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    private String file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.thumbsup
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    private Integer thumbsup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.time
     *
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.id
     *
     * @return the value of timeline.id
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.id
     *
     * @param id the value for timeline.id
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.userid
     *
     * @return the value of timeline.userid
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.userid
     *
     * @param userid the value for timeline.userid
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.text
     *
     * @return the value of timeline.text
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.text
     *
     * @param text the value for timeline.text
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.file
     *
     * @return the value of timeline.file
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.file
     *
     * @param file the value for timeline.file
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public void setFile(String file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.thumbsup
     *
     * @return the value of timeline.thumbsup
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public Integer getThumbsup() {
        return thumbsup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.thumbsup
     *
     * @param thumbsup the value for timeline.thumbsup
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public void setThumbsup(Integer thumbsup) {
        this.thumbsup = thumbsup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.time
     *
     * @return the value of timeline.time
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.time
     *
     * @param time the value for timeline.time
     * @mbggenerated Wed May 16 17:01:30 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}