package com.ygy.model;

import java.util.Date;

public class Usertimeline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertimeline.userid
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertimeline.tid
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertimeline.time
     *
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertimeline.userid
     *
     * @return the value of usertimeline.userid
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertimeline.userid
     *
     * @param userid the value for usertimeline.userid
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertimeline.tid
     *
     * @return the value of usertimeline.tid
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertimeline.tid
     *
     * @param tid the value for usertimeline.tid
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertimeline.time
     *
     * @return the value of usertimeline.time
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertimeline.time
     *
     * @param time the value for usertimeline.time
     * @mbggenerated Mon May 21 15:24:22 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}