eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name:   comment
  datasource:
    url: jdbc:mysql://localhost/springcloud?characterEncoding=utf-8
    username: root
    password: ygy123
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl